### ISSUE TITLE
QEMU failure on macos 20230812.3 

### ISSUE THREAD

**Issue by shrink** [douglascamata/setup-docker-macos-action#12] opened 2023-08-19 16:31 UTC
https://github.com/actions/runner-images/issues/8104

I was investigating why this action was randomly failing for me: turns out, sometimes the runner a Job is allocated to has macos version `20230812.3` (broken) and sometimes it has `20230812.1` (working).

I'm not sure if you want to include the workaround in the action itself, but there's a comment here about it in case you do: https://github.com/actions/runner-images/issues/8104#issuecomment-1683702972

**Comment by douglascamata** [comment] 2023-08-21 09:21
Wow, thanks for digging this one out, @shrink.

I think for now I'll try to not do anything about it, as forcing the downgrade/reinstall of QEMU wastes a lot of CI minutes (it's the slowest part of the whole action). 

But if this starts being too annoying I might include the fix from the comment you suggested. Likely there would be another input to the action to enable the fix, so that it becomes easy to remove from the action itself when the problem is solved on the images.

**Comment by douglascamata** [comment] 2023-08-21 21:13
Got bitten by this too much already and pushed a fix. Should be fixed now.

**Closed by douglascamata** 2023-08-21 21:13 UTC
Labels: bug, dependencies
