### ISSUE TITLE
colima Waiting for the essential requirement 1 of 4: "ssh"

### ISSUE THREAD

**Issue by AlvoBen** [douglascamata/setup-docker-macos-action#39] opened 2024-09-15 11:54 UTC
My pipeline keeps getting stack on: colima Waiting for the essential requirement 1 of 4: "ssh"
![image](https://github.com/user-attachments/assets/c288be8e-deb1-40b6-ada1-c47657e133b0)
Is there any solution for it?

**Comment by douglascamata** [comment] 2024-09-15 12:19
Duplicate of #37. We are trying some stuff there. Seems like some QEMU interactions with the image from Colima are not ending well.

**Closed by douglascamata** 2024-09-15 12:19 UTC
