### ISSUE TITLE
Action fails because of some homebrew error: "fatal: protocol error: bad pack header"

### ISSUE THREAD

**Issue by limpbrains** [douglascamata/setup-docker-macos-action#6] opened 2023-06-29 12:28 UTC
https://github.com/synonymdev/bitkit/actions/runs/5401517464/jobs/9835786665

```
Run douglascamata/setup-docker-macos-action@v1-alpha
  env:
    NO_FLIPPER: 1
    BUILDCACHE_DIR: /Users/runner/work/bitkit/bitkit/.buildcache
    BUILDCACHE_MAX_CACHE_SIZE: 500000000
    BUILDCACHE_DEBUG: 2
    BUILDCACHE_LOG_FILE: /Users/runner/work/bitkit/bitkit/.buildcache/buildcache.log
Run brew update --preinstall
  brew update --preinstall
  brew_repository="$(brew --repository)"
  mkdir -p .github
  cat "$brew_repository/Library/Taps/homebrew/homebrew-core/Formula/colima.rb" > .github/brew-colima
  cat "$brew_repository/Library/Taps/homebrew/homebrew-core/Formula/docker.rb" > .github/brew-docker
  cat "$brew_repository/Library/Taps/homebrew/homebrew-core/Formula/docker-compose.rb" > .github/brew-docker-compose
  shell: /bin/bash --noprofile --norc -e -o pipefail {0}
  env:
    NO_FLIPPER: 1
    BUILDCACHE_DIR: /Users/runner/work/bitkit/bitkit/.buildcache
    BUILDCACHE_MAX_CACHE_SIZE: 500000000
    BUILDCACHE_DEBUG: 2
    BUILDCACHE_LOG_FILE: /Users/runner/work/bitkit/bitkit/.buildcache/buildcache.log
remote: fatal: object c1719cc0b55ef2442207965a5a83ff070820b786 cannot be read        
remote: aborting due to possible repository corruption on the remote side.
fatal: protocol error: bad pack header
Error: Fetching /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core failed!
==> Homebrew is run entirely by unpaid volunteers. Please consider donating:
  https://github.com/Homebrew/brew#donations

==> Auto-updated Homebrew!
Updated 5 taps (homebrew/cask, homebrew/bundle, homebrew/services, mongodb/brew and aws/tap).
==> New Casks
drata-agent
picoscope
rio
score

You have 1 outdated formula and 1 outdated cask installed.

Error: Process completed with exit code 1.
```

**Comment by douglascamata** [comment] 2023-06-29 13:05
@limpbrains seems to be an issue with Homebrew. The logs seem to indicate so and according to this issue in Homebrew, the error is related to Github being inaccessible (i.e. temporary downtime): https://github.com/Homebrew/brew/issues/15610.

Considering this, I'm closing this issue. Let me know if you can confirm the issue is with the action and not Homebrew, then I can reopen.

**Closed by douglascamata** 2023-06-29 13:05 UTC

**Comment by limpbrains** [comment] 2023-06-29 13:09
Thank you!
